# -*- coding: utf-8 -*-
# Deployment settings for BallGame.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
<<<<<<< HEAD
cmdline = ['C:/Marmalade/7.3/s3e/makefile_builder/mkb.py', 'd:/src/marmalade/BallGame/BallGame.mkb', '--buildenv=VC12X', '--fake-vc-call', '--deploy-only']
mkb = 'd:/src/marmalade/BallGame/BallGame.mkb'
=======
cmdline = ['C:/Marmalade/7.3/s3e/makefile_builder/mkb.py', 'c:/Matz_Stuff/src/BallGame/BallGame.mkb', '--buildenv=VC12X', '--debug', '--x86', '--no-ide', '--execute', '--deploy-only']
mkb = 'c:/Matz_Stuff/src/BallGame/BallGame.mkb'
>>>>>>> origin/master
mkf = ['c:\\marmalade\\7.3\\modules\\iwutil\\iwutil.mkf', 'c:\\marmalade\\7.3\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'c:\\marmalade\\7.3\\modules\\third_party\\libpng\\libpng.mkf', 'c:\\marmalade\\7.3\\modules\\third_party\\zlib\\zlib.mkf', 'c:\\marmalade\\7.3\\modules\\iw2dscenegraphcore\\iw2dscenegraphcore.mkf', 'c:\\marmalade\\7.3\\modules\\iw2dscenegraph\\iw2dscenegraph.mkf', 'c:\\marmalade\\7.3\\modules\\iw2d\\iw2d.mkf', 'c:\\marmalade\\7.3\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\7.3\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\7.3\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\7.3\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\7.3\\extensions\\pvrtextool\\pvrtextool.mkf', 'c:\\marmalade\\7.3\\modules\\iwgxfont\\iwgxfont.mkf', 'c:\\marmalade\\7.3\\modules\\third_party\\tiniconv\\tiniconv.mkf', 'c:\\marmalade\\7.3\\modules\\iwtween\\iwtween.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Matz_Stuff/src/BallGame\data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'BallGame'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'BallGame'
    long_caption = 'BallGame'
    version = [0, 0, 1]
    config = ['c:/Matz_Stuff/src/BallGame/data/app.icf']
    data_dir = 'c:/Matz_Stuff/src/BallGame/data'
    iphone_link_lib = []
    osx_ext_dll = ['c:/marmalade/7.3/extensions/pvrtextool/lib/osx/libPVRTexTool.dylib']
    ws8_ext_capabilities = []
    android_external_res = []
    win32_ext_dll = ['c:/marmalade/7.3/extensions/pvrtextool/lib/win32/PVRTexTool.dll']
    wp8_ext_capabilities = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = []
    android_extra_application_manifest = []
    ws8_ext_native_dll = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    linux_ext_lib = []
    ws8_ext_managed_dll = []
    ws81_ext_sdk_ref_file = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    android_external_jars = []
    android_supports_gl_texture = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = []
    ws81_ext_sdk_ref = []
    iphone_link_opts = []
    ws81_ext_native_dll = []
    wp8_ext_managed_dll = []
    android_so = []
    osx_extra_res = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'c:/Matz_Stuff/src/BallGame/build_ballgame_vc12x/Debug_BallGame_VC12X_gcc_x86/BallGame.so',
                   'release' : r'c:/Matz_Stuff/src/BallGame/build_ballgame_vc12x/Release_BallGame_VC12X_gcc_x86/BallGame.so',
                 },
         'gcc_x86_tizen' : {
                   'debug'   : r'c:/Matz_Stuff/src/BallGame/build_ballgame_vc12x/Debug_BallGame_VC12X_gcc_x86_tizen/BallGame.s86',
                   'release' : r'c:/Matz_Stuff/src/BallGame/build_ballgame_vc12x/Release_BallGame_VC12X_gcc_x86_tizen/BallGame.s86',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Matz_Stuff/src/BallGame/build_ballgame_vc12x/Debug_BallGame_VC12X_gcc_mips/BallGame.so',
                   'release' : r'c:/Matz_Stuff/src/BallGame/build_ballgame_vc12x/Release_BallGame_VC12X_gcc_mips/BallGame.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Matz_Stuff/src/BallGame/build_ballgame_vc12x/Debug_BallGame_VC12X_gcc_arm/BallGame.s3e',
                   'release' : r'c:/Matz_Stuff/src/BallGame/build_ballgame_vc12x/Release_BallGame_VC12X_gcc_arm/BallGame.s3e',
                 },
         'mips' : {
                   'debug'   : r'c:/Matz_Stuff/src/BallGame/build_ballgame_vc12x/Debug_BallGame_VC12X_gcc_mips/BallGame.so',
                   'release' : r'c:/Matz_Stuff/src/BallGame/build_ballgame_vc12x/Release_BallGame_VC12X_gcc_mips/BallGame.so',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'c:/Matz_Stuff/src/BallGame/build_ballgame_vc12x/Debug_BallGame_VC12X_gcc_x86_android/BallGame.so',
                   'release' : r'c:/Matz_Stuff/src/BallGame/build_ballgame_vc12x/Release_BallGame_VC12X_gcc_x86_android/BallGame.so',
                 },
         'arm' : {
                   'debug'   : r'c:/Matz_Stuff/src/BallGame/build_ballgame_vc12x/Debug_BallGame_VC12X_arm/BallGame.s3e',
                   'release' : r'c:/Matz_Stuff/src/BallGame/build_ballgame_vc12x/Release_BallGame_VC12X_arm/BallGame.s3e',
                 },
         'x86' : {
                   'debug'   : r'c:/Matz_Stuff/src/BallGame/build_ballgame_vc12x/Debug_BallGame_VC12X_x86/BallGame.s86',
                   'release' : r'c:/Matz_Stuff/src/BallGame/build_ballgame_vc12x/Release_BallGame_VC12X_x86/BallGame.s86',
                 },
        }
    arm_arch = ''
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()
